name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build & Export static site
        env:
          NEXT_PUBLIC_TWILIO_VERIFICATION: ${{ secrets.TWILIO_DOMAIN_VERIFICATION }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          npm run build
          npx next export
          cp CNAME out/CNAME || true
          touch out/.nojekyll
          echo "TWILIO_VERIFICATION_SET=$([ -n "${NEXT_PUBLIC_TWILIO_VERIFICATION}" ] && echo true || echo false)" >> $GITHUB_STEP_SUMMARY
          echo "API_BASE_URL_SET=$([ -n "${NEXT_PUBLIC_API_BASE_URL}" ] && echo true || echo false)" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
